language: rust
dist: trusty
rust:
  - nightly-2018-03-18
cache: cargo
addons:
  postgresql: '9.5'
before_script:
  - pip install 'travis-cargo<0.2' --user
  - export PATH=$HOME/.local/bin:$PATH
script:
  - (cd wundergraph_derive && cargo rustc --no-default-features --features "lint $BACKEND" -- -Zno-trans)
  - (cd wundergraph && cargo rustc --no-default-features --features "lint $BACKEND extras" -- -Zno-trans)
  - (cd wundergraph_example && cargo rustc --no-default-features --features "lint $BACKEND" -- -Zno-trans)
env:
  matrix:
    - BACKEND=sqlite
    - BACKEND=postgres
branches:
  only:
    - master
