[workspace]
members = [
    "wundergraph",
    "wundergraph_derive",
    "wundergraph_example",
]

[replace]
"diesel:1.1.1" = { git = "https://github.com/weiznich/diesel", rev = "09f9a83c255" }
"diesel_migrations:1.1.0" = { git = "https://github.com/weiznich/diesel", rev = "09f9a83c255" }
"migrations_internals:1.1.0" = { git = "https://github.com/weiznich/diesel", rev = "09f9a83c255" }
"migrations_macros:1.1.0" = { git = "https://github.com/weiznich/diesel", rev = "09f9a83c255" }
"diesel_derives:1.1.0" = { git = "https://github.com/weiznich/diesel", rev = "09f9a83c255" }
"juniper:0.9.2" = { git = "https://github.com/weiznich/juniper/", rev = "682664b44" }
"juniper_codegen:0.9.2" = { git = "https://github.com/weiznich/juniper/", rev = "682664b44" }
"juniper_rocket:0.1.2" = { git = "https://github.com/weiznich/juniper/", rev = "682664b44" }
