[package]
name = "wundergraph"
version = "0.1.0"
authors = ["Georg Semmler <georg_semmler_05@web.de>"]
license = "MIT OR Apache-2.0"

[dependencies]
serde = "1"
diesel = { version = "=1.3.3", features = ["r2d2"]}
juniper = "=0.10.0"
indexmap = "1"
wundergraph_derive = { path = "../wundergraph_derive" }
uuid = { version = "0.6", optional = true }
chrono = { version = "0.4", optional = true }
failure = "0.1"
log = "0.4"

[features]
default = ["sqlite", "postgres", "extras"]
debug = ["wundergraph_derive/debug"]
sqlite = ["diesel/sqlite", "wundergraph_derive/sqlite"]
postgres = ["diesel/postgres", "wundergraph_derive/postgres"]
extras = ["chrono", "uuid"]
